Otel example with Kubernetes and JavaScript
DataDog/opentelemetry-examples pull request #61
Opened 2024-02-20 18:51 UTC by wantsui

### What does this PR do?

This PR walks through the steps to submit traces (to the http endpoint) when using OpenTelemetry with Kubernetes via two approaches:
- Via Datadog Operator
- Via Helm

![image](https://github.com/DataDog/opentelemetry-examples/assets/26727996/9aa4951b-e372-4099-838d-a5ad6173be13)

### Motivation

We currently don't have full end to end docs covering the process and this demonstrates the minimal setup required.

Please let me know if the container tagging is implemented correctly has I currently don't have container information 🤔

2024-03-05 17:05 UTC, mx-psi requested changes

2024-03-05 17:05 UTC, mx-psi commented on apps/kubernetes-express-otel/README.md
> +This can be done by execing into the app pod and sending manual requests:
I would add the command needed for doing this, given that we have added commands for other 'simple' steps

2024-03-05 17:05 UTC, mx-psi commented on apps/kubernetes-express-otel/express-otel-app/app.yaml
> +           value: "http://$(HOST_IP):4318/v1/traces"
Per [the spec](https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_endpoint), `OTEL_EXPORTER_OTLP_ENDPOINT` is 
> A base endpoint URL **for any signal type**, with an optionally-specified port number. Helpful for when you’re sending more than one signal to the same endpoint and want one environment variable to control the endpoint.

but here you are passing the traces endpoint.

To fix this we can either pass the generic endpoint:
```suggestion
         - name: OTEL_EXPORTER_OTLP_ENDPOINT
           value: "http://$(HOST_IP):4318"
```

or use the traces-specific environment variable:
```suggestion
         - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
           value: "http://$(HOST_IP):4318/v1/traces"
```

2024-03-05 17:05 UTC, mx-psi commented on apps/kubernetes-express-otel/express-otel-app/instrumentation.js
> +  traceExporter: new OTLPTraceExporter({url: process.env.OTEL_EXPORTER_OTLP_ENDPOINT}),
After following the previous suggestion the config here is no longer needed:
```suggestion
  traceExporter: new OTLPTraceExporter(),
```
It was needed before because if not it would try and append the traces specific path and end up trying to send things to `http://$(HOST_IP):4318/v1/traces/v1/traces`

2024-03-05 19:19 UTC, wantsui commented on apps/kubernetes-express-otel/express-otel-app/app.yaml
> +           value: "http://$(HOST_IP):4318/v1/traces"
Oh! I see the difference now, when I read https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/ .

2024-03-05 20:14 UTC, wantsui commented on apps/kubernetes-express-otel/README.md
> +This can be done by execing into the app pod and sending manual requests:
Done, let me know if this looks good!

The only mystery left that I have is why I don't have container tags in this setup (like what I would normally get with our Datadog Tracing Libraries) 🤔

2024-03-06 08:24 UTC, mx-psi approved these changes

2024-03-06 08:25 UTC, mx-psi commented on apps/kubernetes-express-otel/README.md
> +This can be done by execing into the app pod and sending manual requests:
I don't think we support this yet for traces in OTel. We have support on metrics, but traces remain TBD.

2024-03-06 08:25 UTC, mx-psi commented
@wantsui Will merge this by EOD unless you raise any objections :)

2024-03-07 10:57 UTC, merged